# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_axi_dma_3_0/quad_dma_axi_dma_3_0.xci
# IP: The module: 'quad_dma_axi_dma_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_axi_dma_3_0/quad_dma_axi_dma_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'quad_dma_axi_dma_3_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_axi_dma_3_0/quad_dma_axi_dma_3_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'quad_dma_axi_dma_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_axi_dma_3_0/quad_dma_axi_dma_3_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'quad_dma_axi_dma_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_axi_dma_3_0/quad_dma_axi_dma_3_0.xci
# IP: The module: 'quad_dma_axi_dma_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_axi_dma_3_0/quad_dma_axi_dma_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'quad_dma_axi_dma_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_axi_dma_3_0/quad_dma_axi_dma_3_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'quad_dma_axi_dma_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_axi_dma_3_0/quad_dma_axi_dma_3_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'quad_dma_axi_dma_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
