#!/usr/bin/env bash

cd ~/work/zdma/doc

latexmk --shell-escape -lualatex -outdir=build main.tex

for f in build/*.gnuplot
do
	gnuplot $f
done
#echo >> main.tex
#latexmk --shell-escape -lualatex -outdir=build main.tex

cd -

