#!/usr/bin/env bash

cd ~/work/zdma/doc

#latexmk --shell-escape -lualatex -outdir=build main.tex
lualatex --shell-escape -output-directory=build ./main.tex
#| grep -v erfull | grep -v texmf | grep -v Citation

for f in build/*.gnuplot
do
	gnuplot $f
done
#echo >> main.tex
#latexmk --shell-escape -lualatex -outdir=build main.tex

cd -

