#!/usr/bin/env sh

PBLOCK_LIST="zcore16_0 zcore16_1 zcore16_2 zcore16_3 \
		 zcore16_4 zcore16_5 zcore16_6 zcore16_7 \
		 zcore16_8 zcore16_9 zcore16_10 zcore16_11 \
		 zcore16_12 zcore16_13 zcore16_14 zcore16_15"
CORE_LIST="loopback gauss sobel emboss outline sharpen negative contrast threshold"

top="zed_asym_cc"
solution="solution_16"

rm -rf ./prj
mkdir ./prj

for pblock in $PBLOCK_LIST
do
	mkdir ./prj/$pblock
	for core in $CORE_LIST
	do
		for file in ../cores/$core/${solution}/impl/ip/hdl/verilog/* ../base/base.srcs/sources_1/bd/${top}/ip/${top}_${pblock}_0/synth/${top}_${pblock}_0.v
		do
			echo "verilog xil_defaultLib $file" >> ./prj/$pblock/$core.prj
		done
	done
done
