#!/usr/bin/env bash
TARGET="../../yocto/meta-local/recipes-bsp/zdma-firmware/files"

rm -f $TARGET/*

for f in bitstream/*pcap*bin
do
	install -m 644 $f "$TARGET/`echo $f | sed 's/bitstream\///;s/config_//;s/_pblock_/\./;s/_partial_pcap//'`"
done

install -m 644 bitstream/config_loopback.bit ../../image/download.bit

for f in $TARGET/*.bin
do
	xz --check=crc32 --lzma2=dict=512KiB $f
done

