#!/usr/bin/env sh

instance_name="zcore64"
proj_dir="../base_sym_zedboard_2/"
proj_name="base_sym_zedboard"
cores_dir="../cores"
top="sym_pb4"
solution="solution_64"
INSTANCE_LIST=`printf "${instance_name}_%d " {0..5}`
CORE_LIST="loopback gauss sobel emboss outline sharpen negative contrast threshold"

rm -rf ./prj/*  ./bit ./hd_visual ./synth ./impl ./dcp/*.dcp *.log \
	*.html *.xml vivado* fsm_encoding.os

design_dir="${proj_dir}/${proj_name}.srcs/sources_1/bd/${top}"
for instance in $INSTANCE_LIST
do
	module_name=`grep -E ${top}.*${instance}$ ${design_dir}/hdl/${top}.v | gawk '{print $1}'`
	module_file="${design_dir}/ip/${module_name}/synth/${module_name}.v"

	for core in $CORE_LIST
	do
		core_files="${cores_dir}/${core}/${solution}/impl/ip/hdl/verilog/*"
		for file in ${core_files} ${module_file}
		do
			[ ! -f ${file} ] && echo "Oops! File ${file} was not found, please fix the script!" && exit
			echo "verilog xil_defaultLib ${file}" >> ./prj/${instance}_${core}.prj
		done
	done
done
