# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/quad_dma/quad_dma.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==quad_dma || ORIG_REF_NAME==quad_dma}]

# IP: bd/quad_dma/ip/quad_dma_axi_dma_0_0/quad_dma_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==quad_dma_axi_dma_0_0 || ORIG_REF_NAME==quad_dma_axi_dma_0_0}]

# IP: bd/quad_dma/ip/quad_dma_axi_dma_1_0/quad_dma_axi_dma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==quad_dma_axi_dma_1_0 || ORIG_REF_NAME==quad_dma_axi_dma_1_0}]

# IP: bd/quad_dma/ip/quad_dma_axi_dma_2_0/quad_dma_axi_dma_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==quad_dma_axi_dma_2_0 || ORIG_REF_NAME==quad_dma_axi_dma_2_0}]

# IP: bd/quad_dma/ip/quad_dma_axi_dma_3_0/quad_dma_axi_dma_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==quad_dma_axi_dma_3_0 || ORIG_REF_NAME==quad_dma_axi_dma_3_0}]

# IP: bd/quad_dma/ip/quad_dma_axi_gpio_0_0/quad_dma_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==quad_dma_axi_gpio_0_0 || ORIG_REF_NAME==quad_dma_axi_gpio_0_0}]

# IP: bd/quad_dma/ip/quad_dma_axi_mem_intercon_0/quad_dma_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==quad_dma_axi_mem_intercon_0 || ORIG_REF_NAME==quad_dma_axi_mem_intercon_0}]

# IP: bd/quad_dma/ip/quad_dma_processing_system7_0_0/quad_dma_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==quad_dma_processing_system7_0_0 || ORIG_REF_NAME==quad_dma_processing_system7_0_0}]

# IP: bd/quad_dma/ip/quad_dma_ps7_0_axi_periph_0/quad_dma_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==quad_dma_ps7_0_axi_periph_0 || ORIG_REF_NAME==quad_dma_ps7_0_axi_periph_0}]

# IP: bd/quad_dma/ip/quad_dma_rst_ps7_0_100M_0/quad_dma_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==quad_dma_rst_ps7_0_100M_0 || ORIG_REF_NAME==quad_dma_rst_ps7_0_100M_0}]

# IP: bd/quad_dma/ip/quad_dma_xlconcat_0_0/quad_dma_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==quad_dma_xlconcat_0_0 || ORIG_REF_NAME==quad_dma_xlconcat_0_0}]

# IP: bd/quad_dma/ip/quad_dma_xbar_1/quad_dma_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==quad_dma_xbar_1 || ORIG_REF_NAME==quad_dma_xbar_1}]

# IP: bd/quad_dma/ip/quad_dma_xbar_0/quad_dma_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==quad_dma_xbar_0 || ORIG_REF_NAME==quad_dma_xbar_0}]

# IP: bd/quad_dma/ip/quad_dma_auto_pc_4/quad_dma_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==quad_dma_auto_pc_4 || ORIG_REF_NAME==quad_dma_auto_pc_4}]

# IP: bd/quad_dma/ip/quad_dma_auto_pc_3/quad_dma_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==quad_dma_auto_pc_3 || ORIG_REF_NAME==quad_dma_auto_pc_3}]

# IP: bd/quad_dma/ip/quad_dma_auto_pc_2/quad_dma_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==quad_dma_auto_pc_2 || ORIG_REF_NAME==quad_dma_auto_pc_2}]

# IP: bd/quad_dma/ip/quad_dma_auto_pc_1/quad_dma_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==quad_dma_auto_pc_1 || ORIG_REF_NAME==quad_dma_auto_pc_1}]

# IP: bd/quad_dma/ip/quad_dma_auto_pc_0/quad_dma_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==quad_dma_auto_pc_0 || ORIG_REF_NAME==quad_dma_auto_pc_0}]

# XDC: bd/quad_dma/quad_dma_ooc.xdc
