# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.cache/wt [current_project]
set_property parent.project_path /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/hdl/quad_dma_wrapper.v
add_files /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/quad_dma.bd
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_axi_dma_0_0/quad_dma_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_axi_dma_0_0/quad_dma_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_axi_dma_0_0/quad_dma_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_axi_dma_1_0/quad_dma_axi_dma_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_axi_dma_1_0/quad_dma_axi_dma_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_axi_dma_1_0/quad_dma_axi_dma_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_axi_dma_2_0/quad_dma_axi_dma_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_axi_dma_2_0/quad_dma_axi_dma_2_0.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_axi_dma_2_0/quad_dma_axi_dma_2_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_axi_dma_3_0/quad_dma_axi_dma_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_axi_dma_3_0/quad_dma_axi_dma_3_0.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_axi_dma_3_0/quad_dma_axi_dma_3_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_axi_gpio_0_0/quad_dma_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_axi_gpio_0_0/quad_dma_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_axi_gpio_0_0/quad_dma_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_processing_system7_0_0/quad_dma_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_rst_ps7_0_100M_0/quad_dma_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_rst_ps7_0_100M_0/quad_dma_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_rst_ps7_0_100M_0/quad_dma_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_xbar_1/quad_dma_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_xbar_0/quad_dma_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_auto_pc_4/quad_dma_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_auto_pc_3/quad_dma_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_auto_pc_2/quad_dma_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_auto_pc_1/quad_dma_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/ip/quad_dma_auto_pc_0/quad_dma_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/quad_dma_ooc.xdc]
set_property is_locked true [get_files /home/igalanommatis/work/zdma/zedboard/hardware/quad_dma/quad_dma.srcs/sources_1/bd/quad_dma/quad_dma.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top quad_dma_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef quad_dma_wrapper.dcp

catch { report_utilization -file quad_dma_wrapper_utilization_synth.rpt -pb quad_dma_wrapper_utilization_synth.pb }
