#!/bin/sh
x="\e[1;92m"
y="\e[39m"

case $1 in
"reload")
	cp ../dma/dma.sdk/axidma_wrapper.hdf system.hdf
	cp ../dma/dma.runs/impl_1/axidma_wrapper.bit download.bit
	;;
"reconf")
	petalinux-config --get-hw-description .
	[ `grep EXTRA_IMAGE_FEATURES ./build/conf/local.conf` ] || echo 'EXTRA_IMAGE_FEATURES="debug-tweaks"' >> ./build/conf/local.conf
	sed '/inherit extrausers/d;/EXTRA_USERS_PARAMS/d' -i ./project-spec/meta-plnx-generated/recipes-core/images/petalinux-user-image.bb
	;;
"cbuild")
	petalinux-build -c zdma || exit
	petalinux-build -c bench
	petalinux-build -x package
	;;
"build")
	petalinux-build
	;;
"run")
	xsdb ./arm_reset.tcl
	petalinux-package --prebuilt --clean --fpga ./download.bit
	petalinux-boot --jtag --prebuilt 3
	;;
"con"*)
	picocom -b115200 /dev/ttyACM0
	;;
"clean")
	rm *.log *.jou
	;;
*)
	echo -e ""\
		"$x reload$y: refresh hardware project files (HDF and BIT).\n"	\
		"$x reconf$y: reread HDF and run project configuration.\n"	\
		"$x cbuikd$y: build user components.\n"				\
		"$x build$y:  build everything.\n"				\
		"$x run$y:    boot the project to the connected board\n"	\
		"$x con$y:    launch serial terminal to target board.\n"
	;;
esac


