#!/bin/sh
MODULE="zdma"
[ $# -eq 0 ] && action="init" || action=$1

case $action in
"prog")
	echo "Programming $2.bin..."
	tftp -gr $2.bin 192.168.2.1
	echo 1 > /sys/class/xdevcfg/xdevcfg/device/is_partial_bitstream
	cat $2.bin > /dev/xdevcfg
	zapp 1 1 v
	mv out0.jpg $2.jpg
	tftp -pl $2.jpg 192.168.2.1
	;;
"gdb")
	gdbserver 192.168.2.2:1234 /usr/bin/zapp
	;;
*)
	echo "Unknown command!"
	;;
esac

