#!/bin/sh
MODULE="zdma"
[ $# -eq 0 ] && action="init" || action=$1

case $action in
"init")
	for MODULE in zdma zoled
	do
	        major=`awk "\\$2==\"$MODULE\" { print \\$1 }" /proc/devices`
		[ "$major" -eq "" ] && { echo "Could not find $MODULE in /proc/devices"; exit -1; }
		rm -f /dev/$MODULE
		mknod /dev/$MODULE c $major 0
	done

	echo "hello world" > /home/root/loopback.bit
	;;
"gdb")
	ip link set up dev eth0
	ip addr add 192.168.2.2/24 dev eth0
	gdbserver 192.168.2.2:1234 /usr/bin/libzdma
	;;
*)
	echo "Unknown command!"
	;;
esac

